### PR TITLE
Added serializer back in

### PR DESCRIPTION
**Pull request by xWorkerBeex**

### CODE REVIEW

**Comment by Alsciende** [comment]
This is useless. The package is on packagist: https://packagist.org/packages/alsciende/serializer-bundle.

**Comment by fatihi** [comment]
Ah good to know, thank you! There is an issue with saving the decks and it came from your commit, so we were basically just trying to figure out what caused it

**Comment by fatihi** [comment]
Does that mean we can just add the package to "require"?

**Comment by Alsciende** [comment]
Yes, like every other packages, it just needs to be required and composed will find it automatically through packagist. That’s how I updated composer.lock, and it works.

I don’t know why there’s an issue with deck saving though...

**Comment by Alsciende** [comment]
I didn’t run the behat tests. That could give us a hint.

**Pull request merged**
